<h2>login/index</h2>
<div>
	<form method="POST" action="">
		<div>
			<label for="user">Usuario</label>
		</div>
		<div>
			<input type="email" name="user" id="user" />

		</div>
			<br />
		<div>
			<label for="pass">Senha</label>
		</div>
		<div>
			<input type="password" name="pass" id="pass" />
		</div>
		<div>
			<br />
			<input type="submit" name="btnEtrar" id="btnEntrar" value="Entrar" />
		</div>
	</form>
</div>